### ISSUE TITLE
Hardcoded MC paths

### ISSUE THREAD

**Issue by cassie-fletcher** [modexp/analysis#2]
There are hardcoded MC paths on lines 130 and 301 of analyzer.C.  If they are not correct, daqana will segmentation fault.  

Ideally, these paths should be passed from the daqprocessor.py python code when it verifies that these MC paths exist.  Alternatively, these could be hardcoded at the top so at least they're easier to find.

**Comment by acolijn** [comment]
Hi Cassie,
In principle the analysis code knows howto find these files. But will have a look.
AP

**Comment by adambrown1** [comment]
I believe this is now fixed, see:
https://github.com/modexp/analysis/blob/acebbd14942f0e29f38cd40413cecd0177bc557f/calibration/analyzer.C#L132-L141

It does require that the MC files are available in the working directory, unfortunately it is not so simple to make it possible to only have them in the same directory as the script. At the moment this is handled in daqana by creating a symlink at run-time.
https://github.com/modexp/daqana/blob/df660b8714d01eafd31ed7a86cd186dcc193c260/daqprocessor_single_calibrate.py#L243-L245

**Comment by JoranAngevaare** [comment]
Maybe Sander or someone else from Nikhef can push the changes that have been made on the analyzer.c to also include the background spectrum into the fit.

 

Cheers, Joran

 

Van: Adam Brown [mailto:notifications@github.com] 
Verzonden: vrijdag 3 november 2017 18:29
Aan: modexp/analysis <analysis@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [modexp/analysis] Hardcoded MC paths (#2)

 

I believe this is now fixed, see:
https://github.com/modexp/analysis/blob/acebbd14942f0e29f38cd40413cecd0177bc557f/calibration/analyzer.C#L132-L141

It does require that the MC files are available in the working directory, unfortunately it is not so simple to make it possible to only have them in the same directory as the script. At the moment this is handled in daqana by creating a symlink at run-time.
https://github.com/modexp/daqana/blob/df660b8714d01eafd31ed7a86cd186dcc193c260/daqprocessor_single_calibrate.py#L243-L245
